### ISSUE TITLE
"Projection Matrixについて"の"視野のオフセットの計算"の図がおかしい

### ISSUE THREAD

**Issue by gyojir** [shikihuiku/shikihuiku.github.io#2]
[Projection Matrixについて](https://shikihuiku.github.io/post/projection_matrix)内の[視野のオフセットの計算](https://shikihuiku.github.io/post/projection_matrix/Perspective_Z3_hu770a23a06793a884f7075f1eec4e4997_39058_2000x2000_fit_lanczos_3.PNG)の図で、視野のオフセットが視錐台全体を平行移動したものとして表されてしまっています。

この図ですと、View座標系からNDC座標系に変換するときのオフセット(このページで言うところのbとd)が、本来はNDC座標系におけるオフセットであるのに対して、View座標系におけるオフセットに見えてしまいます。
(NDC座標系におけるオフセットはイメージ的には視錐台をせん断変形するようなものなので視錐台の原点は変わらないはずです)

**Comment by shikihuiku** [comment]
ご指摘ありがとうございます。確かにView座標系で記述された図なので間違っていました。
図を変更するとともに、少し文章も変えてみました。よろしければReviewしていただけると幸いです。
よろしくお願いいたします。

**Comment by gyojir** [comment]
修正ありがとうございます。
問題ないと思います。
